"""
PDF generation utilities using reportlab.

Two reports are supported:
  - build_prediction_pdf: a single, branded prediction report
  - build_history_pdf: a tabular export of all prediction history
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable,
)

BRAND_COLOR = colors.HexColor("#4F46E5")
BRAND_DARK = colors.HexColor("#1E1B4B")


def _base_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name="BrandTitle", fontSize=20, textColor=BRAND_DARK,
        spaceAfter=4, fontName="Helvetica-Bold",
    ))
    styles.add(ParagraphStyle(
        name="BrandSubtitle", fontSize=10, textColor=colors.grey, spaceAfter=16,
    ))
    styles.add(ParagraphStyle(
        name="SectionHeader", fontSize=13, textColor=BRAND_COLOR,
        spaceBefore=14, spaceAfter=6, fontName="Helvetica-Bold",
    ))
    return styles


def build_prediction_pdf(record: dict, reasons: list, tips: list, filepath: str):
    styles = _base_styles()
    doc = SimpleDocTemplate(filepath, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm)
    story = []

    story.append(Paragraph("NovaCredit AI", styles["BrandTitle"]))
    story.append(Paragraph("AI-Powered Banking Risk Intelligence — Automated Loan Risk Assessment Report", styles["BrandSubtitle"]))
    story.append(HRFlowable(width="100%", color=BRAND_COLOR, thickness=1))

    story.append(Paragraph("Prediction Summary", styles["SectionHeader"]))
    risk_color = colors.HexColor("#DC2626") if record["prediction"] == "High Risk" else colors.HexColor("#059669")
    summary_data = [
        ["Prediction", record["prediction"]],
        ["Default Probability", f"{record['prediction_probability']}%"],
        ["Report Generated", record["timestamp"]],
    ]
    summary_table = Table(summary_data, colWidths=[6 * cm, 9 * cm])
    summary_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (1, 0), (1, 0), risk_color),
        ("FONTNAME", (1, 0), (1, 0), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
    ]))
    story.append(summary_table)

    story.append(Paragraph("Customer Information", styles["SectionHeader"]))
    customer_data = [
        ["Name", record.get("customer_name", "-")],
        ["Age", str(record.get("age", "-"))],
        ["Gender", record.get("gender", "-")],
        ["Marital Status", record.get("marital_status", "-")],
        ["City", record.get("city", "-")],
        ["Education", record.get("education_level", "-")],
        ["Employment", record.get("employment_status", "-")],
    ]
    story.append(_two_col_table(customer_data))

    story.append(Paragraph("Financial & Loan Information", styles["SectionHeader"]))
    financial_data = [
        ["Income", f"₹{record.get('income', '-')}"],
        ["Credit Score", str(record.get("credit_score", "-"))],
        ["Years Employed", str(record.get("years_employed", "-"))],
        ["Loan Amount", f"₹{record.get('loan_amount', '-')}"],
        ["Loan Term (months)", str(record.get("loan_term", "-"))],
        ["Existing Debt", f"₹{record.get('existing_debt', '-')}"],
        ["Previous Loans", str(record.get("previous_loans", "-"))],
        ["Late Payments", str(record.get("late_payments", "-"))],
        ["Monthly Expenses", f"₹{record.get('monthly_expenses', '-')}"],
        ["Savings Balance", f"₹{record.get('savings_balance', '-')}"],
        ["Debt-to-Income Ratio", str(record.get("debt_to_income_ratio", "-"))],
        ["Loan Purpose", record.get("loan_purpose", "-")],
    ]
    story.append(_two_col_table(financial_data))

    story.append(Paragraph("Risk Factors", styles["SectionHeader"]))
    for r in reasons:
        story.append(Paragraph(f"• {r}", styles["Normal"]))

    story.append(Paragraph("Recommendations", styles["SectionHeader"]))
    for t in tips:
        story.append(Paragraph(f"• {t}", styles["Normal"]))

    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", color=colors.lightgrey, thickness=0.5))
    story.append(Paragraph(
        "Generated by NovaCredit AI — Powered by Random Forest ML Model",
        styles["BrandSubtitle"],
    ))

    doc.build(story)


def _two_col_table(data):
    table = Table(data, colWidths=[6 * cm, 9 * cm])
    table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
    ]))
    return table


def build_history_pdf(records: list, filepath: str):
    styles = _base_styles()
    doc = SimpleDocTemplate(filepath, pagesize=A4, topMargin=1.5 * cm, bottomMargin=1.5 * cm)
    story = [
        Paragraph("NovaCredit AI — Prediction History", styles["BrandTitle"]),
        Paragraph(f"Total Records: {len(records)}", styles["BrandSubtitle"]),
        HRFlowable(width="100%", color=BRAND_COLOR, thickness=1),
        Spacer(1, 10),
    ]

    header = ["ID", "Date", "Customer", "City", "Credit Score", "Loan Amount", "Prediction", "Prob %"]
    rows = [header]
    for r in records:
        rows.append([
            str(r["id"]), r["timestamp"][:10], r.get("customer_name", "-"),
            r.get("city", "-"), str(r.get("credit_score", "-")),
            str(r.get("loan_amount", "-")), r.get("prediction", "-"),
            str(r.get("prediction_probability", "-")),
        ])

    table = Table(rows, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_COLOR),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 7.5),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.lightgrey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F5F5FF")]),
    ]))
    story.append(table)
    doc.build(story)
